### ISSUE TITLE
Bug - "Alterar meus dados"

### ISSUE THREAD

**Issue by kevenjesus** [valdiney/Your-task-manager#1]
Olá tem um bug na parte de alterar meus dados ...
deixe o nome em branco e clique em cadastrar/alterar!!!
ele cai nesta pagina totalmente sem formatação.
http://valdiney.meximas.com/tarefas/editar_usuarios.php

**Comment by valdiney** [comment]
Erro corrigido! Esse ai o problema era no controller no momento de tentar voltar para a página anterior usando o header("Location").

Valeu por reportar o erro.

**Comment by valdiney** [comment]
t
