### ISSUE TITLE
Bug - "Visualizar tarefa completa"

### ISSUE THREAD

**Issue by kevenjesus** [valdiney/Your-task-manager#2]
Olá,

na parte de visualizar tarefa completa, colocando um id não existente na url ele não me retorna nada, um exemplo "tarefa inexistente ou uma simples pagina 404"

http://valdiney.meximas.com/tarefas/visualizar_tarefa_completa.php?textoCompleto&id=0

**Comment by valdiney** [comment]
Corrigido! Valeu por reportar este erro cara.
